-- 返回视图结构
SELECT 
COMMENTS,COLUMN_NAME,DATA_TYPE_NAME,
LENGTH,SCALE,IS_NULLABLE,DEFAULT_VALUE
FROM SYS.VIEW_COLUMNS
-- 数据库名
WHERE SCHEMA_NAME = '_SYS_BIC'
-- 视图名
AND VIEW_NAME = 'ZPBI/CAL_ZRMM_CGJS'
ORDER BY POSITION;

